id: P005535
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG3673
  title: རྫོགས་པ་ཆེན་པོ་ཀློང་ཆེན་སྙིང་ཐིག་གི་ཐུན་མོང་དང་ཐུན་མོང་མ་ཡིན་པའི་ཁྲིད་ཡིག་
  author: ''
  volumes:
    f16c1495204e40e7a0a05f3aee349759:
      image_group_id: I1KG3701
      title: ''
      volume_number: 1
      total_pages: 70
      base_file: v001.txt
