id: I94F46616
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T17:10:24+00:00'
last_modified: '2022-06-08T04:44:04.178956+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3673
  title: རྫོགས་པ་ཆེན་པོ་ཀློང་ཆེན་སྙིང་ཐིག་གི་ཐུན་མོང་དང་ཐུན་མོང་མ་ཡིན་པའི་ཁྲིད་ཡིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6E54:
      image_group_id: I1KG3701
      title: ''
      total_pages: 70
      order: 1
      base_file: 6E54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
